# .github/workflows/main.yml
name: PTT Auto Login CI

on:
  # 1. 允許手動觸發 (方便我們馬上測試)
  workflow_dispatch:

  # 2. 設定排程，每日自動執行
  schedule:
    # 使用 UTC 時間，'30 16 * * *' 代表每天的 16:30 UTC
    # 換算成台灣時間 (UTC+8) 就是午夜 00:30
    - cron: '5 0,4,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虛擬環境

    steps:
      # 步驟 1: 取得專案的原始碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步驟 2: 設定 Python 執行環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # 指定使用的 Python 版本

      # 步驟 3: 安裝程式所需的套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          
      # 步驟 4: 執行 PTT 登入腳本 (第一個帳號)
      - name: Run PTT auto login script (Account 1)
        run: python PttAuto.py ${{ secrets.PTT_ID }} ${{ secrets.PTT_PASS }} ${{ secrets.TG_BOT_TOKEN }} ${{ secrets.TG_USER_ID }}

      # 步驟 5: 執行 PTT 登入腳本 (第二個帳號)
      - name: Run PTT auto login script (Account 2)
        run: python PttAuto.py ${{ secrets.PTT_ID2 }} ${{ secrets.PTT_PASS }} ${{ secrets.TG_BOT_TOKEN }} ${{ secrets.TG_USER_ID }}
