# .github/workflows/main.yml
name: PTT Auto Login CI

on:
  # 1. 允許手動觸發 (方便我們馬上測試)
  workflow_dispatch:

  # 2. 設定排程，每日自動執行
  schedule:
    # 使用 UTC 時間，'30 16 * * *' 代表每天的 16:30 UTC
    # 換算成台灣時間 (UTC+8) 就是午夜 00:30
    - cron: '5 0,4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虛擬環境

    steps:
      # 步驟 1: 取得專案的原始碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步驟 2: 設定 Python 執行環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # 指定使用的 Python 版本

      # 步驟 3: 安裝程式所需的套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 asyncssh # 根據專案 requirements.txt 安裝
          
      - name: Debug - 檢視工作目錄與檔案結構
        run: |
          echo "========================================="
          echo "1. 目前所在的工作目錄 (pwd):"
          pwd
          echo "========================================="
          echo "2. 列出所有檔案與資料夾 (ls -R):"
          ls -R
          echo "========================================="
          
      # 步驟 4: 執行 PTT 登入腳本
      - name: Run PTT auto login script
        # 我們不再切換工作目錄，而是直接從專案根目錄執行，並給出檔案的完整相對路徑。
        # 這是最穩定、最不會出錯的方法。
        run: python PttAuto.py ${{ secrets.PTT_ID }} ${{ secrets.PTT_PASS }}

      - name: Run PTT_2 auto login script
        # 我們不再切換工作目錄，而是直接從專案根目錄執行，並給出檔案的完整相對路徑。
        # 這是最穩定、最不會出錯的方法。
        run: python PttAuto.py ${{ secrets.PTT_ID2 }} ${{ secrets.PTT_PASS }}
